### ISSUE TITLE
Where do you get data to annotate bcf files with?

### ISSUE THREAD

**Issue by endrebak** [shiquan/vcfanno#1]
I am looking for what kind of mutation a variant is (missense, anon etc) and where it is in relation to genes/other features.

This should potentially be added to the docs, as finding the info to annotate with is also something many users wont know how to do :)

Thanks. Looking forward to trying your package!

**Comment by shiquan** [comment]
Sorry about the poor documentation of bcfanno. I am trying to fix this issue ASAP.

For now, to interpret the functional types of variants, you could download the databases and configure file from http://public.genomics.org.cn/bcfanno/databases/hg19/. 

You may find a genome annotation file and transcripts reference on this server. I have defined a new Genome Element Annotation (GEA) format to store the transcripts, genes, and motifs. I will also release a new tool to generate GEA file from any GFF or GTF. 

Thank you for your testing. Please let me know if you have any further questions.

**Comment by endrebak** [comment]
Yes, I understand how it is hard to write good docs when there is so much code work to do. I think it will help you in the end (more citations etc) to have a few example use cases and guide though.

Thanks for the prompt reply.
