### ISSUE TITLE
Is there a way to build a customized version of GEA from some pubic database resources?

### ISSUE THREAD

**Issue by wulj2** [shiquan/vcfanno#2]

**Comment by shiquan** [comment]
Hi, I have a plan to redesign the GEA format and this program, but will not release it recently. I will let you know when available. Sorry about the inconvenience.

**Comment by wulj2** [comment]
Wow, expecting your reconstruct, In my opinion, the loc array of transcript pos might be appended in the GEA record during GEA construction to reduce exhaust in online evaluation from alignment CIGAR string if your redesign still depends on that CIGAR

**Comment by wulj2** [comment]
Can I guess that the alignment cigar comes from alignment between UCSC public refrna(query) and manually constructed mRNA seq according to UCSC refgene Exon coordinates? And bwa alike aligned might do the work to generate the cigar after which change CLIP to INS?
